# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3ec7c6c684c715fda25a0f5c2bf2d4e78e30b79fe6b7265d2a164348a6c748a1bf662373f14c7617430ed11508204744b7432ddd0a862401abd80761d41ec7e

test:
  secret_key_base: 36795e945cabb4c3adef173c2eae395ce1b875e716089a30355a69d7887de95f44eb3491877784069f9e2fa1f2c2e1675072440939d667a0616b47c02b4e0b5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
